#Remove Savanna Animals
removeSavannaAnimals = true
#Remove Swamp Animals
removeSwampAnimals = true
#Remove Jungle Animals
removeJungleAnimals = true
#Remove Forest Animals
removeForestAnimals = true
#Add Jungle Animals
addJungleAnimals = true
#Spawn Hazelnut Bush
spawnHazelnutBush = true
#Pelican Spawn Weight
#Range: 0 ~ 1000
pelicanSpawnWeight = 5
#Pelican Min Group Size
#Range: 1 ~ 10
pelicanMinGroupSize = 3
#Pelican Max Group Size
#Range: 1 ~ 10
pelicanMaxGroupSize = 5
#Deer Spawn Weight
#Range: 0 ~ 1000
deerSpawnWeight = 12
#Deer Min Group Size
#Range: 1 ~ 10
deerMinGroupSize = 2
#Deer Max Group Size
#Range: 1 ~ 10
deerMaxGroupSize = 4
#Raccoon Spawn Weight
#Range: 0 ~ 1000
raccoonSpawnWeight = 8
#Raccoon Min Group Size
#Range: 1 ~ 10
raccoonMinGroupSize = 2
#Raccoon Max Group Size
#Range: 1 ~ 10
raccoonMaxGroupSize = 3
#Squirrel Spawn Weight
#Range: 0 ~ 1000
squirrelSpawnWeight = 8
#Squirrel Min Group Size
#Range: 1 ~ 10
squirrelMinGroupSize = 2
#Squirrel Max Group Size
#Range: 1 ~ 10
squirrelMaxGroupSize = 2
#Red Wolf Spawn Weight
#Range: 0 ~ 1000
redWolfSpawnWeight = 10
#Red Wolf Min Group Size
#Range: 1 ~ 10
redWolfMinGroupSize = 2
#Red Wolf Max Group Size
#Range: 1 ~ 10
redWolfMaxGroupSize = 4
#Owl Spawn Weight
#Range: 0 ~ 1000
owlSpawnWeight = 12
#Owl Min Group Size
#Range: 1 ~ 10
owlMinGroupSize = 3
#Owl Max Group Size
#Range: 1 ~ 10
owlMaxGroupSize = 3
#Boar Spawn Weight
#Range: 0 ~ 1000
boarSpawnWeight = 14
#Boar Min Group Size
#Range: 1 ~ 10
boarMinGroupSize = 4
#Boar Max Group Size
#Range: 1 ~ 10
boarMaxGroupSize = 5
#Bison Spawn Weight
#Range: 0 ~ 1000
bisonSpawnWeight = 10
#Bison Min Group Size
#Range: 1 ~ 10
bisonMinGroupSize = 3
#Bison Max Group Size
#Range: 1 ~ 10
bisonMaxGroupSize = 5
#Turkey Spawn Weight
#Range: 0 ~ 1000
turkeySpawnWeight = 12
#Turkey Min Group Size
#Range: 1 ~ 10
turkeyMinGroupSize = 3
#Turkey Max Group Size
#Range: 1 ~ 10
turkeyMaxGroupSize = 5
#Dog Spawn Weight
#Range: 0 ~ 1000
dogSpawnWeight = 2
#Dog Min Group Size
#Range: 1 ~ 10
dogMinGroupSize = 1
#Dog Max Group Size
#Range: 1 ~ 10
dogMaxGroupSize = 1
#MiniSheep Spawn Weight
#Range: 0 ~ 1000
minisheepSpawnWeight = 8
#MiniSheep Min Group Size
#Range: 1 ~ 10
minisheepMinGroupSize = 2
#MiniSheep Max Group Size
#Range: 1 ~ 10
minisheepMaxGroupSize = 4
#Penguin Spawn Weight
#Range: 0 ~ 1000
penguinSpawnWeight = 10
#Penguin Min Group Size
#Range: 1 ~ 10
penguinMinGroupSize = 2
#Penguin Max Group Size
#Range: 1 ~ 10
penguinMaxGroupSize = 5
#Cassowary Spawn Weight
#Range: 0 ~ 1000
cassowarySpawnWeight = 12
#Cassowary Min Group Size
#Range: 1 ~ 10
cassowaryMinGroupSize = 3
#Cassowary Max Group Size
#Range: 1 ~ 10
cassowaryMaxGroupSize = 4
#Flamingo Spawn Weight
#Range: 0 ~ 1000
flamingoSpawnWeight = 9
#Flamingo Min Group Size
#Range: 1 ~ 10
flamingoMinGroupSize = 3
#Flamingo Max Group Size
#Range: 1 ~ 10
flamingoMaxGroupSize = 6
#Hedgehog Spawn Weight
#Range: 0 ~ 1000
hedgehogSpawnWeight = 10
#Hedgehog Min Group Size
#Range: 1 ~ 10
hedgehogMinGroupSize = 2
#Hedgehog Max Group Size
#Range: 1 ~ 10
hedgehogMaxGroupSize = 4

